spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ProshkaAnastasia/HighloadedSystems-Lab2
          default-label: main
          search-paths: "/config-repo"

server:
  port: ${CONFIG_PORT:8888}

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.actuate: DEBUG
